// packages/vue/src/views/cart/CartItem.vue
<template>
  <li class="cart-item">
    {{ cartItem.name }}
    <div class="cart-item__image" :style="itemImageClass" />
    <div class="cart-item__editor">
      <div class="cart-item__editor__unit">
        <span class="cart-item__editor__unit__price">
          {{ cartItem.unitPrice }}円
        </span>
        &nbsp;×&nbsp;
        <label>
          <input
            class="cart-item__editor__unit__count"
            type="number"
            min="1"
            :value="count"
            @change="onChangeCount($event.target.value)"
          />個
        </label>
      </div>
      <div class="cart-item__editor__price">計{{ cartItem.payment }}円</div>
      <button @click="onRemove(cartItem)">カートから取り除く</button>
      <button v-if="willPurchase" @click="onBuyLater(cartItem)">後で買う</button>
      <button v-else @click="onBuyNow(cartItem)">今すぐ買う</button>
    </div>
  </li>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Emit, Prop } from "vue-property-decorator";
import { CartItem, CountInCart } from "@example/domain-cart/model";

@Component
export default class CartItemView extends Vue {
  @Prop({ required: true })
  cartItem!: CartItem;

  get willPurchase(): boolean {
    return this.cartItem.willBuyNow;
  }

  get count(): CountInCart {
    return this.cartItem.count;
  }

  get itemImageClass(): Record<string, string> {
    const base = {
      "background-image": `url(${this.cartItem.picture.url})`,
      "background-position": "center",
      "background-repeat": "no-repeat",
      "background-size": "contain",
      width: "300px",
      height: "300px",
    };

    if (this.willPurchase) {
      return base;
    }

    return {
      ...base,
      "background-color": "lightgray",
      "background-blend-mode": "multiply",
    };
  }

  @Emit("remove")
  onRemove(_item: CartItem): void {}

  @Emit("buy-later")
  onBuyLater(_item: CartItem): void {}

  @Emit("buy-now")
  onBuyNow(_item: CartItem): void {}

  onChangeCount(newCount: string): void {
    this.emitChangeCount(this.cartItem, CountInCart.parse(newCount));
  }

  @Emit("change-count")
  emitChangeCount(_item: CartItem, _newCount: CountInCart): void {}
}
</script>

<style scoped>
.cart-item {
  font-size: 24px;
  list-style: none;
  width: 300px;
}
.cart-item__editor__unit {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
}
.cart-item__editor__unit__count {
  font-size: 20px;
  width: 50px;
}
.cart-item__editor__price {
  font-weight: bold;
  margin-bottom: 10px;
  margin-top: 10px;
}
button {
  font-size: 20px;
  width: 220px;
}
</style>

// packages/react/src/cart/CartItem.tsx
import { CartItem as CartItemObj, CountInCart } from '@example/domain-cart/dist/model'
import React, { ChangeEvent } from 'react'

export interface CartItemProps {
  cartItem: CartItemObj
  onRemove: () => void
  onBuyLater: () => void
  onBuyNow: () => void
  onChangeCount: (newCount: CountInCart) => void
}

export function CartItem(props: CartItemProps) {
  const cartItem = props.cartItem

  const handleChangeCount = ({ target }: ChangeEvent<HTMLInputElement>) =>
    props.onChangeCount(CountInCart.parse(target.value))

  return (
    <li className="cart-item" key={cartItem.id}>
      {cartItem.name}
      <div className="cart-item__image" style={itemImageClass(cartItem)} />
      <div className="cart-item__editor">
        <div className="cart-item__editor__unit">
          <span className="cart-item__editor__unit__price">
            {cartItem.unitPrice.toNumber()}円
          </span>
          &nbsp;×&nbsp;
          <label>
            <input
              className="cart-item__editor__unit__count"
              type="number"
              value={cartItem.count.toNumber()}
              min="1"
              onChange={handleChangeCount}
            />個
          </label>
        </div>
        <div className="cart-item__editor__price">計{cartItem.payment}円</div>
        <button onClick={props.onRemove}>カートから取り除く</button>
        {
          cartItem.willBuyNow ?
            <button onClick={props.onBuyLater}>後で買う</button> :
            <button onClick={props.onBuyNow}>今すぐ買う</button>
        }
      </div>
    </li>
  )
}

const itemImageClass = (cartItem: CartItemObj): Record<string, string> => {
  const base = {
    backgroundImage: `url(${cartItem.picture.url})`,
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    width: "300px",
    height: "300px",
  };

  if (cartItem.willBuyNow) {
    return base;
  }

  return {
    ...base,
    backgroundColor: "lightgray",
    backgroundBlendMode: "multiply",
  };
}
