// packages/react/src/cart/CartItem.tsx
import { CartItem as CartItemObj, CountInCart } from '@example/domain-cart/dist/model'
import React, { ChangeEvent } from 'react'

export interface CartItemProps {
  cartItem: CartItemObj
  onRemove: () => void
  onBuyLater: () => void
  onBuyNow: () => void
  onChangeCount: (newCount: CountInCart) => void
}

export function CartItem(props: CartItemProps) {
  const cartItem = props.cartItem

  const handleChangeCount = ({ target }: ChangeEvent<HTMLInputElement>) =>
    props.onChangeCount(CountInCart.parse(target.value))

  return (
    <li className="cart-item" key={cartItem.id}>
      {cartItem.name}
      <div className="cart-item__image" style={itemImageClass(cartItem)} />
      <div className="cart-item__editor">
        <div className="cart-item__editor__unit">
          <span className="cart-item__editor__unit__price">
            {cartItem.unitPrice.toNumber()}円
          </span>
          &nbsp;×&nbsp;
          <label>
            <input
              className="cart-item__editor__unit__count"
              type="number"
              value={cartItem.count.toNumber()}
              min="1"
              onChange={handleChangeCount}
            />個
          </label>
        </div>
        <div className="cart-item__editor__price">計{cartItem.payment}円</div>
        <button onClick={props.onRemove}>カートから取り除く</button>
        {
          cartItem.willBuyNow ?
            <button onClick={props.onBuyLater}>後で買う</button> :
            <button onClick={props.onBuyNow}>今すぐ買う</button>
        }
      </div>
    </li>
  )
}

const itemImageClass = (cartItem: CartItemObj): Record<string, string> => {
  const base = {
    backgroundImage: `url(${cartItem.picture.url})`,
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    width: "300px",
    height: "300px",
  };

  if (cartItem.willBuyNow) {
    return base;
  }

  return {
    ...base,
    backgroundColor: "lightgray",
    backgroundBlendMode: "multiply",
  };
}

// packages/vue/src/components/CartItem.vue
<template>
  <li class="cart-item cart-item-list__item">
    <div class="cart-item__image" :style="imageStyle"></div>
    <div class="cart-item__editor">
      <div class="cart-item__editor__unit">
        <span class="cart-item__editor__unit__price">
          {{ item.unitPrice.toNumber() }}円
        </span>
        ×
        <label>
          <input
            :id="`cart-item__editor__unit__count--${item.id}`"
            type="number"
            min="1"
            class="cart-item__editor__unit__count"
            :value="item.count.toNumber()"
            @change="handleCountChange"
          >個
        </label>
      </div>
      <div class="cart-item__editor__price">計{{ item.payment }}円</div>
      <button @click="handleRemove">カートから取り除く</button>
      <button v-if="item.willBuyNow" @click="handleBuyLater">後で買う</button>
      <button v-else @click="handleBuyNow">今すぐ買う</button>
    </div>
  </li>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { CartItem, CountInCart } from '@example/domain/model/index'

const props = defineProps<{
  item: CartItem
}>()

const emit = defineEmits<{
  remove: [item: CartItem]
  buyLater: [item: CartItem]
  buyNow: [item: CartItem]
  changeCount: [item: CartItem, count: CountInCart]
}>()

const imageStyle = computed(() => {
  const base = {
    'background-image': `url(${props.item.picture.url})`,
    'background-position': 'center',
    'background-repeat': 'no-repeat',
    'background-size': 'contain',
    'width': '300px',
    'height': '300px'
  }

  if (props.item.willBuyNow) {
    return base
  }

  return {
    ...base,
    'background-color': 'lightgray',
    'background-blend-mode': 'multiply'
  }
})

const handleRemove = () => {
  emit('remove', props.item)
}

const handleBuyLater = () => {
  emit('buyLater', props.item)
}

const handleBuyNow = () => {
  emit('buyNow', props.item)
}

const handleCountChange = (event: Event) => {
  const element = event.target as HTMLInputElement
  const newCount = CountInCart.parse(element.value)
  emit('changeCount', props.item, newCount)
}
</script>
